parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     rcs_data
    database_user:     root
    database_password: "b0ar!!"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            HereIsASlightlyMoreSecretTokenIMadeJustForYou
